name: Update PageSpeed Insights

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 24 hours at midnight UTC
  workflow_dispatch:  # Allows manual triggering as well

jobs:
  update-insights:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch PageSpeed Insights
        run: |
          curl "http://localhost:3000/?url=https://github.com/NalinDalal&strategy=desktop&categories=performance,accessibility,seo,best-practices&legend=false" > insights.svg

      - name: Commit and push updates
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add insights.svg
          git commit -m "Update PageSpeed Insights"
          git push
